import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { readFile } from "node:fs/promises";
import { compose, renderWav } from "../src/lib/music/composer";
import { defaultChoices } from "../src/lib/music/knowledge";
import { MUSIC_PATH, PROFILE_PATH } from "../src/lib/routes";

test("the composer keeps a tune across tempo changes and exports bounded PCM audio", async () => {
  const slow = compose({ ...defaultChoices, pace: "slow" }, 2026, 2);
  const fast = compose({ ...defaultChoices, pace: "lively" }, 2026, 2);
  expect(slow.melody.map(note => note.midi)).toEqual(fast.melody.map(note => note.midi));
  expect(slow.duration).toBeGreaterThan(fast.duration);
  expect(compose(defaultChoices, 20).melody).not.toEqual(compose(defaultChoices, 21).melody);
  expect(compose({ ...defaultChoices, beat: false }, 2026).notes.some(note => note.voice === "kick")).toBe(false);
  const blob = await renderWav(slow);
  const wav = Buffer.from(await blob.arrayBuffer());
  expect(wav.toString("ascii", 0, 4)).toBe("RIFF");
  expect(wav.toString("ascii", 8, 12)).toBe("WAVE");
  expect(wav.readUInt32LE(24)).toBe(22050);
  expect(wav.readUInt32LE(40)).toBe(wav.length - 44);
  let peak = 0;
  for (let i = 44; i < wav.length; i += 2) peak = Math.max(peak, Math.abs(wav.readInt16LE(i)));
  expect(peak).toBeGreaterThan(1000);
  expect(peak).toBeLessThanOrEqual(22938);
  const abort = new AbortController(); abort.abort();
  await expect(renderWav(slow, abort.signal)).rejects.toThrow();
});

test("learn, carry a choice into creation, play, download, and reach the team", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page).toHaveURL(new RegExp(MUSIC_PATH));
  await expect(page.getByRole("heading", { name: "How fast does music move?" })).toBeVisible();
  expect(await page.locator("audio").evaluateAll(elements => elements.every(element => (element as HTMLAudioElement).paused))).toBe(true);
  const initialAxe = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(initialAxe.violations.map(v => ({ rule: v.id, targets: v.nodes.map(n => n.target) }))).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("knowledge-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "Listen to A slow stroll" }).click();
  const example = page.getByLabel("Lesson example player");
  await expect(example).toHaveJSProperty("paused", false);
  await page.getByRole("button", { name: "Stop all sound" }).click();
  await expect(example).toHaveJSProperty("paused", true);
  await page.getByRole("region", { name: "A slow stroll", exact: true }).getByRole("button", { name: /Use this/ }).click();
  await expect(page.getByRole("tab", { name: "Create music", exact: true })).toBeFocused();
  await expect(page.locator(".music-choice").filter({ hasText: "Slow" })).toHaveAttribute("data-state", "on");
  await page.getByLabel("Give it a name").fill("A tune for everyone");
  await page.getByRole("button", { name: "Create my music", exact: true }).click();
  const download = page.getByRole("link", { name: "Download WAV" });
  await expect(download).toBeVisible();
  const song = page.getByLabel("Your music player");
  await expect(song).toHaveJSProperty("paused", true);
  await expect(song).toHaveJSProperty("readyState", 4);
  await page.getByRole("button", { name: "Play my music", exact: true }).click();
  await expect(song).toHaveJSProperty("paused", false);
  await page.getByRole("button", { name: "Stop all sound" }).click();
  await expect(song).toHaveJSProperty("paused", true);
  const downloaded = page.waitForEvent("download");
  await download.click();
  const file = await downloaded;
  expect(file.suggestedFilename()).toBe("A-tune-for-everyone.wav");
  const bytes = await readFile((await file.path())!);
  expect(bytes.toString("ascii", 8, 12)).toBe("WAVE");
  expect(bytes.length).toBeGreaterThan(500000);
  await page.locator(".music-choice").filter({ hasText: "Bells" }).click();
  await expect(page.getByText("Your choices have changed.", { exact: false })).toBeVisible();
  await page.getByRole("tab", { name: "Learn a little" }).click();
  await page.getByRole("tab", { name: "Create music", exact: true }).click();
  await expect(download).toHaveAttribute("href", /^blob:/);
  await page.screenshot({ path: testInfo.outputPath("creator-desktop.png"), fullPage: true });
  await page.getByRole("link", { name: "Team", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(PROFILE_PATH));
  await expect(page.getByRole("heading", { name: "The people behind the idea." })).toBeVisible();
  expect(errors).toEqual([]);
});

test("public learning stays accessible with a protected album, dark mode, and large mobile text", async ({ browser }, testInfo) => {
  const context = await browser.newContext({ baseURL: "http://127.0.0.1:3101", viewport: { width: 390, height: 844 }, colorScheme: "dark", reducedMotion: "reduce" });
  const page = await context.newPage();
  await page.goto("/music-ai-2026");
  await expect(page).toHaveURL(new RegExp(MUSIC_PATH));
  await expect(page.locator("html")).toHaveClass(/dark/);
  await page.getByRole("button", { name: "Bigger text", exact: true }).click();
  await expect(page.locator(".music-studio")).toHaveAttribute("data-large-text", "true");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const learnAxe = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(learnAxe.violations.map(v => ({ rule: v.id, targets: v.nodes.map(n => n.target) }))).toEqual([]);
  await page.getByRole("tab", { name: "Create music", exact: true }).click();
  const slow = page.locator(".music-choice").filter({ hasText: "Slow" });
  await slow.focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("radio", { name: "Steady", exact: true })).toBeFocused();
  await page.keyboard.press("Space");
  await expect(page.locator(".music-choice").filter({ hasText: "Steady" })).toHaveAttribute("data-state", "on");
  await page.screenshot({ path: testInfo.outputPath("creator-mobile-dark.png"), fullPage: true });
  const creatorAxe = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(creatorAxe.violations.map(v => ({ rule: v.id, targets: v.nodes.map(n => n.target) }))).toEqual([]);
  await page.setViewportSize({ width: 320, height: 760 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("link", { name: "Team", exact: true }).click();
  await expect(page.getByLabel("Team password", { exact: true })).toBeVisible();
  await context.close();
});
